Sugar Factory
settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE pull request #832
Opened 2021-11-18 13:42 UTC by Butterspekulatius

I hope it works now. Sorry it didn´t worked the first time.

And I´m already using Notepad++

2021-11-18 13:44 UTC, Butterspekulatius commented
Can somehow delete or ignore those earlier commits?
I tried to tidy it up but now its looks like a mess.

2021-11-18 16:02 UTC, settintotrieste requested changes

2021-11-18 16:02 UTC, settintotrieste commented on CWE/common/production_types.txt
> +		fruit = 1,5
It should be fruit = 1.5 instead of fruit = 1,5

2021-11-18 16:02 UTC, settintotrieste commented on CWE/common/production_types.txt
> +	value = 2,6
It should be value = 2.6 instead of value = 2,6

2021-11-18 16:03 UTC, settintotrieste commented
I’m afraid it’s not possible to remove those commits unless you create a separate branch and then PR that one.

2021-11-18 16:06 UTC, settintotrieste commented
If you want to add localisation, you can copy one of the entries in localisation/text.csv to create a description for sugar factory. You’ll have to open the localisation file with word pad though as notepad++ will mess with the character encoding of csv files.

2021-11-18 16:09 UTC, Butterspekulatius commented
Ok. I change the comma into a point.

Should I create a branch to make a single PR with the changes and the loc? So its only a single commit?

And thank you for the help. I realy appreciate it.

2021-11-19 02:09 UTC, settintotrieste requested changes

2021-11-19 02:09 UTC, settintotrieste commented on CWE/localisation/text.csv
> +sugar_factory; Sugar Factory;;;;;;;;;;;;x,,;;;;;;;;;;;;;;;;;
There's an extra space in "sugar_factory; Sugar Factory"

2021-11-19 02:09 UTC, settintotrieste commented on CWE/localisation/text.csv
> +sugar_factory_desc; A refinery where sugar beets are processed into raw sugar.;;;;;;;;;;;;x,,;;;;;;;;;;;;;;;;;
There's an extra space in "sugar_factory_desc; A refinery..."

2021-11-19 02:10 UTC, settintotrieste commented
No problem and sure, you can make a separate branch to make the commits look neater.

2021-11-19 10:36 UTC, Butterspekulatius commented
Ok, then I will change the loc and make the whole thing a seperate branch.

2021-11-19 11:59 UTC, settintotrieste commented
Thanks!

2021-11-19 11:59 UTC, closed without merging